---
kind: pipeline
type: docker
name: frontend_test_pipeline

platform:
  os: linux
  arch: amd64

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: whitelist
    host:
      path: /etc/docker/daemon.json
  - name: toolkit
    host:
      path: /data/drone_data

steps:
  - name: gcloud test
    pull: if-not-exists
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    commands:
      - gcloud auth activate-service-account --key-file=/data/drone_data/auth.json
      - gcloud compute instances list